// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddsjinvivcfrjltlwnof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkc2ppbnZpdmNmcmpsdGx3bm9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5NzcyMzUsImV4cCI6MjA3NzU1MzIzNX0.Cbw8AtE5zmcShOjh3pB0h1rwwXE8aIhBiWhIiT6KNTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});